[package]
name = "keg"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

[lib]
name = "libkeg"
path = "src/lib/lib.rs"

[[bin]]
name = "keg"
path = "src/bin/main.rs"